module.exports = {
    "RECIPE_EN_GB" : {
        "fish tacos": " In a nonstick pan, heat over medium high heat the oil and then add the tilapia. Season with half the lime juice, salt, cumin and southwest seasoning. Once that side is cooked, flip and season, cooking till golden. Heat a small pan over medium heat and then spray with cooking spray. Add tortilla, cooking and heating both sides. Fill tortilla with a portion of fish and then top with desired toppings.",
        "Tacos el pastor " : "In a medium saucepan, heat the 1 tablespoon of oil. Add the garlic and cook over moderately high heat, turning occasionally, until lightly browned, about 1 minute. Stir in the oregano, cumin, pepper and cloves and cook until fragrant, about 1 minute. Add the chiles and cook, stirring, until blistered in spots, about 30 seconds. Add the pineapple juice, vinegar and achiote paste and bring to a boil. Remove from the heat and let stand for 5 minutes. Transfer the chile mixture to a blender and puree until smooth. Season with salt. Scrape the marinade into a large, sturdy plastic bag.Add the pork and turn to coat. Set the bag in a small baking dish and refrigerate overnight. Light a grill or preheat a grill pan. Brush the pineapple and onion with oil. Grill over high heat, turning once, until lightly charred and softened, 3 to 5 minutes. Transfer to a carving board and tent with foil. Remove the pork from the marinade. Grill over high heat until lightly charred and just cooked through, 2 to 4 minutes. Transfer to the carving board and let rest for 5 minutes. Cut the pineapple, onion and pork into thin strips and transfer to a bowl. Season with salt. Serve with corn tortillas, chopped cilantro and lime wedges.",
        
        },
    "RECIPE_EN_US" : {
        "fish tacos" : " In a nonstick pan, heat over medium high heat the oil and then add the tilapia. Season with half the lime juice, salt, cumin and southwest seasoning. Once that side is cooked, flip and season, cooking till golden. Heat a small pan over medium heat and then spray with cooking spray. Add tortilla, cooking and heating both sides. Fill tortilla with a portion of fish and then top with desired toppings.",
        "Tacos el pastor " : "In a medium saucepan, heat the 1 tablespoon of oil. Add the garlic and cook over moderately high heat, turning occasionally, until lightly browned, about 1 minute. Stir in the oregano, cumin, pepper and cloves and cook until fragrant, about 1 minute. Add the chiles and cook, stirring, until blistered in spots, about 30 seconds. Add the pineapple juice, vinegar and achiote paste and bring to a boil. Remove from the heat and let stand for 5 minutes. Transfer the chile mixture to a blender and puree until smooth. Season with salt. Scrape the marinade into a large, sturdy plastic bag.Add the pork and turn to coat. Set the bag in a small baking dish and refrigerate overnight. Light a grill or preheat a grill pan. Brush the pineapple and onion with oil. Grill over high heat, turning once, until lightly charred and softened, 3 to 5 minutes. Transfer to a carving board and tent with foil. Remove the pork from the marinade. Grill over high heat until lightly charred and just cooked through, 2 to 4 minutes. Transfer to the carving board and let rest for 5 minutes. Cut the pineapple, onion and pork into thin strips and transfer to a bowl. Season with salt. Serve with corn tortillas, chopped cilantro and lime wedges.",
    }
};