module.exports = {
    "RECIPE_EN_GB" : {
        "fish tacos": " In a nonstick pan, heat over medium high heat the oil and then add the tilapia. Season with half the lime juice, salt, cumin and southwest seasoning. Once that side is cooked, flip and season, cooking till golden. Heat a small pan over medium heat and then spray with cooking spray. Add tortilla, cooking and heating both sides. Fill tortilla with a portion of fish and then top with desired toppings.",
        "tacos al pastor " : "In a medium saucepan, heat the 1 tablespoon of oil. Add the garlic and cook over moderately high heat, turning occasionally, until lightly browned, about 1 minute. Stir in the oregano, cumin, pepper and cloves and cook until fragrant, about 1 minute. Add the chiles and cook, stirring, until blistered in spots, about 30 seconds. Add the pineapple juice, vinegar and achiote paste and bring to a boil. Remove from the heat and let stand for 5 minutes. Transfer the chile mixture to a blender and puree until smooth. Season with salt. Scrape the marinade into a large, sturdy plastic bag.Add the pork and turn to coat. Set the bag in a small baking dish and refrigerate overnight. Light a grill or preheat a grill pan. Brush the pineapple and onion with oil. Grill over high heat, turning once, until lightly charred and softened, 3 to 5 minutes. Transfer to a carving board and tent with foil. Remove the pork from the marinade. Grill over high heat until lightly charred and just cooked through, 2 to 4 minutes. Transfer to the carving board and let rest for 5 minutes. Cut the pineapple, onion and pork into thin strips and transfer to a bowl. Season with salt. Serve with corn tortillas, chopped cilantro and lime wedges.",
        "chicken tacos" :"Prepare grill. Combine first 4 ingredients in a small bowl; rub spice mixture over chicken. Place chicken on grill rack coated with cooking spray; grill 10 minutes on each side or until done. Let stand 5 minutes; chop. Heat tortillas according to package directions. Divide chicken evenly among tortillas; top each tortilla with 2 tablespoons cabbage and 1 teaspoon cheese. Serve with sour cream, if desired.",
        "asada tacos" : "Cover flank steak on one side with the pickled jalapenos, then turn over let sit at room temperature, covered for 1 hour. Preheat the grill or broiler. Season both sides of the steak with salt and pepper and place on a hot grill or under the broiler. Cook the steak for 5 to 6 minutes on each side (for medium rare), and then chop into 1/4-inch pieces. Heat a small saute pan and add 1 tablespoon canola oil. Warm corn tortillas for 30 seconds on each side, adding more oil as necessary. Stack 2 tortillas together, place the meat in the center of the tortillas and top with the onion and cilantro. Drizzle a teaspoon of the salsa de arbol on top of each taco.",
        "tongue tacos" : "Put beef tongue, onion, garlic and bay leaves in a slow cooker and add enough water to cover tongue. Cook overnight on low. You can also gently boil it on the stovetop for 2 hours to 3 hours, until the beef tongue turns very tender.When tongue is cool enough to handle, peel off and discard rough tongue skin.Cut tongue in 1/2-inch slices across grain then into 1/2-inch cubes. It can also be shredded or sliced, depend on the dish you cook. If you won’t serve the tongue soon, store in an airtight container or ziplock bag in the fridge up to 5 days.When ready to serve, heat oil in a large nonstick or cast iron skillet set over medium-high heat until shimmering. Add tongue pieces and cook, stirring occasionally, until tongue is well browned on all sides, 2 to 3 minutes total. Season to taste with salt and pepper.tack 2 tortillas together, place the meat in the center of the tortillas and top with the onion and cilantro. Drizzle a teaspoon of the salsa de arbol on top of each taco."
        },
    "RECIPE_EN_US" : {
        "fish tacos" : " In a nonstick pan, heat over medium high heat the oil and then add the tilapia. Season with half the lime juice, salt, cumin and southwest seasoning. Once that side is cooked, flip and season, cooking till golden. Heat a small pan over medium heat and then spray with cooking spray. Add tortilla, cooking and heating both sides. Fill tortilla with a portion of fish and then top with desired toppings.",
        "tacos al pastor " : "In a medium saucepan, heat the 1 tablespoon of oil. Add the garlic and cook over moderately high heat, turning occasionally, until lightly browned, about 1 minute. Stir in the oregano, cumin, pepper and cloves and cook until fragrant, about 1 minute. Add the chiles and cook, stirring, until blistered in spots, about 30 seconds. Add the pineapple juice, vinegar and achiote paste and bring to a boil. Remove from the heat and let stand for 5 minutes. Transfer the chile mixture to a blender and puree until smooth. Season with salt. Scrape the marinade into a large, sturdy plastic bag.Add the pork and turn to coat. Set the bag in a small baking dish and refrigerate overnight. Light a grill or preheat a grill pan. Brush the pineapple and onion with oil. Grill over high heat, turning once, until lightly charred and softened, 3 to 5 minutes. Transfer to a carving board and tent with foil. Remove the pork from the marinade. Grill over high heat until lightly charred and just cooked through, 2 to 4 minutes. Transfer to the carving board and let rest for 5 minutes. Cut the pineapple, onion and pork into thin strips and transfer to a bowl. Season with salt. Serve with corn tortillas, chopped cilantro and lime wedges.",
        "chicken tacos" :"Prepare grill. Combine first 4 ingredients in a small bowl; rub spice mixture over chicken. Place chicken on grill rack coated with cooking spray; grill 10 minutes on each side or until done. Let stand 5 minutes; chop. Heat tortillas according to package directions. Divide chicken evenly among tortillas; top each tortilla with 2 tablespoons cabbage and 1 teaspoon cheese. Serve with sour cream, if desired.",
        "asada tacos" : "Cover flank steak on one side with the pickled jalapenos, then turn over let sit at room temperature, covered for 1 hour. Preheat the grill or broiler. Season both sides of the steak with salt and pepper and place on a hot grill or under the broiler. Cook the steak for 5 to 6 minutes on each side (for medium rare), and then chop into 1/4-inch pieces. Heat a small saute pan and add 1 tablespoon canola oil. Warm corn tortillas for 30 seconds on each side, adding more oil as necessary. Stack 2 tortillas together, place the meat in the center of the tortillas and top with the onion and cilantro. Drizzle a teaspoon of the salsa de arbol on top of each taco.",
        "tongue tacos" : "Put beef tongue, onion, garlic and bay leaves in a slow cooker and add enough water to cover tongue. Cook overnight on low. You can also gently boil it on the stovetop for 2 hours to 3 hours, until the beef tongue turns very tender.When tongue is cool enough to handle, peel off and discard rough tongue skin.Cut tongue in 1/2-inch slices across grain then into 1/2-inch cubes. It can also be shredded or sliced, depend on the dish you cook. If you won’t serve the tongue soon, store in an airtight container or ziplock bag in the fridge up to 5 days.When ready to serve, heat oil in a large nonstick or cast iron skillet set over medium-high heat until shimmering. Add tongue pieces and cook, stirring occasionally, until tongue is well browned on all sides, 2 to 3 minutes total. Season to taste with salt and pepper.tack 2 tortillas together, place the meat in the center of the tortillas and top with the onion and cilantro. Drizzle a teaspoon of the salsa de arbol on top of each taco."
    }
};